pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/JohnehChuks/DevOps.git', credentialsId: 'github-pat'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'cd dockfolder && docker build -t MydockerImageName .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker stop DockContainer || true'
                sh 'docker rm DockContainer || true'
                sh 'docker run -d --name DockContainer -p 8080:80 MydockerImageName'
            }
        }
    }
}
