pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/JohnehChuks/DevOps.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t MydockerImageName .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker stop DockContainer || true'
                sh 'docker rm DockContainer || true'
                sh 'docker run -d --name DockContainer -p 8080:80 MydockerImageName'
            }
        }
    }
}
